import type { Metadata } from "next";
import { Lilita_One, Roboto } from "next/font/google";
import { auth } from "../auth";
import Header from "@/components/ui-elements/Header";
import "./globals.css";

const lilita_One = Lilita_One({
  variable: "--font-lilita",
  subsets: ["latin"],
  weight: "400",
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: "400"
})

export const metadata: Metadata = {
  title: "tea dawgs",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body>
        <Header session={session} />
        {children}
        </SessionProvider>
      </body>
    </html>
  );
}
